PRAGMA foreign_keys=ON;

/* Institution Information*/
INSERT INTO questions (surveyQuestion, questionID, SurveyID,question, choices, cdsNO) VALUES ("IN1", 80000, 8, "Please confirm your school's URL. You may give us the main URL for your institution or a more specific URL for your distance learning division.","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN2", 8, "In what year did your unit first offer courses or programs via distance learning? Please provide a year greater than 1910 and less than 2020.","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN3", 8, "Approximately how many students (unduplicated headcount) were enrolled in distance learning courses or programs (all types) at your unit in the specified fall term?","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN4", 8, "Can institutionally administered financial aid be applied to programs completed at a distance?","Yes; No; NA","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN5", 8, "Which of the following services are available to distance learning students and are accessible at a distance (through computer, phone, fax, etc.)?","academic advising; bookstore; campus computer network; career placement assistance; email services; library services; tutoring","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN6", 8, "I Does your unit offer entire degree programs through distance learning?","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN7", 8, "Non-Degree-Related Course Subject Areas. In which general undergraduate-level subject areas are courses offered?","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN7", 8, "Non-Degree-Related Course Subject Areas. In which general graduate-level subject areas are courses offered?","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN7", 8, "Non-Degree-Related Course Subject Areas. In which general non-credit subject areas are courses offered?","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN7", 8, "Non-Degree-Related Course Subject Areas. Please indicate the typical per-course cost for your non-degree courses listed above","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN11.A", 8, "Unit Contact: Social Title","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN11.B", 8, "Unit Contact: Name","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN11.C", 8, "Unit Contact: Title","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN11.D", 8, "Unit Contact: Address","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN11.E", 8, "Unit Contact: Phone","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN11.F", 8, "Unit Contact: Fax","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN11.G", 8, "Unit Contact: Email","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN12.A", 8, "Head of Distance Learning Unit: Social Title","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN12.B", 8, "Head of Distance Learning Unit: Name","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN12.C", 8, "Head of Distance Learning Unit: Title","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN12.D", 8, "Head of Distance Learning Unit: Address","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN12.E", 8, "Head of Distance Learning Unit: Phone","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN12.F", 8, "Head of Distance Learning Unit: Fax","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN12.G", 8, "Head of Distance Learning Unit: Email","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN13.A", 8, "Survey Respondent: Social Title","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN13.B", 8, "Survey Respondent: Name","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN13.C", 8, "Survey Respondent: Title","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN13.D", 8, "Survey Respondent: Address","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN13.E", 8, "Survey Respondent: Phone","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN13.F", 8, "Survey Respondent: Fax","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN13.G", 8, "Survey Respondent: Email","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN14.A", 8, "Survey Contact: Social Title","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN14.B", 8, "Survey Contact: Name","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN14.C", 8, "Survey Contact: Title","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN14.D", 8, "Survey Contact: Address","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN14.E", 8, "Survey Contact: Phone","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN14.F", 8, "Survey Contact: Fax","","");
INSERT INTO questions (surveyQuestion, SurveyID,question, choices, cdsNO) VALUES ("IN14.G", 8, "Survey Contact: Email","","");
